### PR TITLE
First draft on analytics page

### PR DESCRIPTION
**Pull request by ilayaperumalg**

### CODE REVIEW

**Comment by cppwfs** [comment]
I reformatted the page  to make it easier to read in text editor.  And one small change.
https://github.com/cppwfs/spring-xd-debs-2015/tree/ilayaperumalg-analytics-page

**Comment by cppwfs** [comment]
Cleaned up format.  One small edit.  Merged

**Comment by ilayaperumalg** [comment]
@cppwfs Looks like this change https://github.com/ilayaperumalg/spring-xd-debs-2015/commit/8693921bf1757883bc60ba4bb0ef8b3391b1d56e wasn't pulled for the merge.

**Comment by ilayaperumalg** [comment]
I had couple of commits on this PR :-)

**Comment by pperalta** [comment]
b908dfe0ed6fa669517955a4d8c84e4d347796c9

**Pull request closed without merging**
