### PR TITLE
Minor changes to "Integrations" section. Refer comments for additional suggestions.

### PR DESCRIPTION
**Pull request by sabbyanandan**

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Perhaps "popular data stores and processing" can be "popular data stores and data processing systems such as MongoDB, Redis, HDFS, Spark, Sqoop, Pig, Hive"

We prove it now :)
https://github.com/spring-projects/spring-xd-samples/tree/master/batch-pig
https://github.com/spring-projects/spring-xd-samples/tree/master/batch-hive

**Comment by sabbyanandan** [comment]
"Thus in cases that the job fails, a job can be designed to be restarted and pickup where it left off or roll- back the changes that were in transaction."

Suggestion: 
"To account for failure scenarios, the workflow in the job can be designed to restart and resume operation or roll-back the transaction altogether."

**Comment by sabbyanandan** [comment]
"Integration Examples"

I like how you're trying to position the stream as "microservice" but in reality XD as a platform enables you to create pipes (service) that can evolve in isolation. Could we perhaps make this distinction clear? It doesn't, but we don't want to let someone think XD is a "microservice" by itself.

**Comment by pperalta** [comment]
Merged as 43b3e1302429ed180f48ae752c838437deb19143

**Pull request closed without merging**
